### ISSUE TITLE
Cheeves 

### ISSUE THREAD

**Issue by Centralan** [Centralan/Minigames#7]
Need to be added : 

Bought one item from a shop. 

Have a total of 50 PvE Points at once. 

Have a total of 100 PvE Points at once. 

Have  a total of 500 PvE Points at once. 

Have a total of 1000 PvE Points at once.

**Comment by Centralan** [comment]
@Exposedgun316

**Comment by Kruithne** [comment]
Just as a note, the 50, 100, 500 and 1000 ones should not be done as completely separate achievements, rather create a template and extend it with variable input to reduce code and make things cleaner.

I believe there is already an example for one of the other achievements that has multiple tiers, maybe the tunnel? Unsure.
